name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout sources"
      uses: actions/checkout@v1
    - name: "Setup Node"
      uses: actions/setup-node@v2-beta
    - name: "Build modules"
      run: chmod 755 .github/workflows/build-all.sh && .github/workflows/build-all.sh